### ISSUE TITLE
Página personal Youssef

### ISSUE THREAD

**Issue by iartuoc** [iartuoc/Machine-Learning#10]
Esta tarea se subdivide en 3:
- Crear página (@yuse2m)
- Revisarla (@ArtesanoMultimedia)
- Subirla a Gsites (@yuse2m)

**Comment by yuse2m** [comment]
En mi documento hay escrito un boceto para probar. aún no está terminado

**Comment by iartuoc** [comment]
Pues si no está terminado, dejamos la tarea en proceso.

**Comment by yuse2m** [comment]
Si está terminado.  Eso es un mensaje antiguo.
